version: "3"

services:
  gateway:
    container_name: "gateway"
    build: ./Gateway
    ports:
      - "3000:3000"
    depends_on:
      - movies
      - security
    networks:
      - network-micro
  monitoreo:
    container_name: "monitoreo"
    build: ./Monitoreo
    ports:
      - "4000:4000"
    networks:
      - network-micro
  log:
    container_name: "log"
    build: ./Logs
    ports:
      - "3032:3032"
    depends_on:
      - dblogs
    networks:
      - network-micro
  movies:
    container_name: "movies"
    build: ./Movies
    ports:
      - "3012:3012"
    depends_on:
      - dbmovies
      - log
    networks:
      - network-micro
  security:
    container_name: "security"
    build: ./Security
    ports:
      - "3022:3022"
    depends_on:
      - dbsecurity
    networks:
      - network-micro
  dbmovies:
    container_name: "dbmovies"
    build: ./MongoMovie
    ports:
      - "27017:27017"
    volumes:
      - "/MongoMovie/data/db:/data/db"
    networks:
      - network-micro
  dbsecurity:
    container_name: "dbsecurity"
    build: ./MongoSecurity
    ports:
      - "27018:27017"
    volumes:
      - "/MongoSecurity/data/db:/data/db"
    networks:
      - network-micro
  dblogs:
    container_name: "dblogs"
    build: ./MongoLog
    ports:
      - "27020:27020"
    volumes:
      - "/MongoLog/data/db:/data/db"
    networks:
      - network-micro

networks:
  network-micro:
