# imagen base
FROM mongo:latest

# variables de entorno
ENV MONGO_INITDB_ROOT_USERNAME=root
ENV MONGO_INITDB_ROOT_PASSWORD=3lVillano

# ejecutar el demonio de Mongo
CMD ["mongod","--port", "27020"]

# puerto a exponer
EXPOSE 27020